#!/usr/bin/env python3
"""Generate the first connected SOMADEX overworld block on three 20x20 GBA layouts.

Technical slots:
- LittlerootTown -> Vela South
- Route101      -> Vela Center
- OldaleTown    -> Vela Resonance Grove

All reachable terrain now uses the owned Vela metatile vocabulary generated by
`generate_vela_tileset.py`; the upstream map/layout IDs remain engine slots only.
"""

import argparse
import struct
from pathlib import Path

from vela_tileset_ids import (
    CRYSTAL,
    DOOR,
    FENCE,
    FLOWERS,
    GROUND,
    HEDGE,
    LAMP,
    PATH,
    PLAZA,
    ROOF,
    SAND,
    SIGN,
    TALL_GRASS,
    TREE,
    WALL,
    WATER,
)

WIDTH = 20
HEIGHT = 20


def blank() -> list[list[int]]:
    return [[GROUND for _ in range(WIDTH)] for _ in range(HEIGHT)]


def stamp_tree(grid: list[list[int]], x: int, y: int) -> None:
    if x < 0 or y < 0 or x + 1 >= WIDTH or y + 1 >= HEIGHT:
        return
    grid[y][x] = TREE[0][0]
    grid[y][x + 1] = TREE[0][1]
    grid[y + 1][x] = TREE[1][0]
    grid[y + 1][x + 1] = TREE[1][1]


def frame(grid: list[list[int]], *, top_exit: bool, bottom_exit: bool) -> None:
    for x in range(0, WIDTH, 2):
        if not (top_exit and 8 <= x <= 10):
            stamp_tree(grid, x, 0)
        if not (bottom_exit and 8 <= x <= 10):
            stamp_tree(grid, x, HEIGHT - 2)
    for y in range(2, HEIGHT - 2, 2):
        stamp_tree(grid, 0, y)
        stamp_tree(grid, WIDTH - 2, y)


def rect(grid: list[list[int]], tile: int, x0: int, y0: int, x1: int, y1: int) -> None:
    for y in range(max(0, y0), min(HEIGHT - 1, y1) + 1):
        for x in range(max(0, x0), min(WIDTH - 1, x1) + 1):
            grid[y][x] = tile


def path_vertical(grid: list[list[int]], x0: int = 8, x1: int = 11) -> None:
    rect(grid, PATH, x0, 0, x1, HEIGHT - 1)


def path_horizontal(grid: list[list[int]], y0: int, y1: int) -> None:
    rect(grid, PATH, 0, y0, WIDTH - 1, y1)


def stamp_building(grid: list[list[int]], x: int, y: int) -> None:
    """Compact 3x3 Vela facade; decorative for this first outdoor block."""
    rect(grid, ROOF, x, y, x + 2, y)
    rect(grid, WALL, x, y + 1, x + 2, y + 2)
    grid[y + 2][x + 1] = DOOR


def stamp_pond(grid: list[list[int]], x0: int, y0: int, x1: int, y1: int) -> None:
    rect(grid, SAND, x0 - 1, y0 - 1, x1 + 1, y1 + 1)
    rect(grid, WATER, x0, y0, x1, y1)


def build_vela_south() -> list[list[int]]:
    """Calm southern approach, waterside pocket and starter plaza."""
    g = blank()
    frame(g, top_exit=True, bottom_exit=False)
    path_vertical(g)

    # Starter plaza creates a readable staging area before entering the town.
    rect(g, PLAZA, 5, 9, 14, 13)
    rect(g, PATH, 8, 9, 11, 13)

    # Small coastal/pond motif introduces Vela's blue-green visual identity.
    stamp_pond(g, 2, 5, 5, 7)
    rect(g, FLOWERS, 13, 5, 16, 7)
    g[8][14] = LAMP
    g[8][5] = SIGN

    # Light fencing guides the player without turning the map into a corridor.
    for x in range(3, 8):
        g[15][x] = FENCE
    for x in range(12, 17):
        g[15][x] = FENCE
    return g


def build_vela_center() -> list[list[int]]:
    """Main Vela slice: Mira, landmark, two facades and first encounter."""
    g = blank()
    frame(g, top_exit=True, bottom_exit=True)
    path_vertical(g)
    path_horizontal(g, 10, 12)

    # Central stone plaza and resonance landmark at the existing interaction tile.
    rect(g, PLAZA, 6, 8, 13, 14)
    rect(g, PATH, 8, 8, 11, 14)
    rect(g, PATH, 6, 10, 13, 12)
    g[10][10] = CRYSTAL
    g[9][7] = LAMP
    g[9][12] = LAMP

    # Two readable Vela facades establish the town instead of an empty route.
    stamp_building(g, 2, 8)
    stamp_building(g, 15, 8)
    g[13][4] = FLOWERS
    g[13][15] = FLOWERS

    # Controlled first encounter remains exactly at x=10,y=16.
    rect(g, TALL_GRASS, 6, 16, 13, 17)
    g[16][8] = PATH
    g[16][9] = PATH
    g[16][11] = PATH
    g[16][12] = PATH

    # A few hedges visually separate the encounter belt from the plaza.
    for x in (4, 5, 14, 15):
        g[15][x] = HEDGE
    return g


def build_vela_grove() -> list[list[int]]:
    """Denser northern resonance grove with a pool and crystal clearing."""
    g = blank()
    frame(g, top_exit=False, bottom_exit=True)
    path_vertical(g)

    # Denser encounter vegetation around the edges, but a clear navigation spine.
    rect(g, TALL_GRASS, 3, 3, 7, 7)
    rect(g, TALL_GRASS, 12, 3, 16, 7)
    rect(g, TALL_GRASS, 3, 12, 7, 15)
    rect(g, TALL_GRASS, 12, 12, 16, 15)

    # Resonance clearing: stone core, crystals and a small water pocket.
    rect(g, PLAZA, 6, 7, 13, 12)
    rect(g, PATH, 8, 6, 11, 15)
    g[9][7] = CRYSTAL
    g[9][12] = CRYSTAL
    g[11][7] = FLOWERS
    g[11][12] = FLOWERS
    stamp_pond(g, 3, 9, 5, 11)

    stamp_tree(g, 3, 4)
    stamp_tree(g, 15, 4)
    stamp_tree(g, 3, 14)
    stamp_tree(g, 15, 14)
    return g


def write_map(root: Path, layout: str, grid: list[list[int]]) -> None:
    if len(grid) != HEIGHT or any(len(row) != WIDTH for row in grid):
        raise SystemExit(f"{layout}: invalid grid dimensions")
    output = root / "data/layouts" / layout / "map.bin"
    if not output.parent.is_dir():
        raise SystemExit(f"missing locked layout directory: {output.parent}")
    payload = b"".join(struct.pack("<H", cell) for row in grid for cell in row)
    expected = WIDTH * HEIGHT * 2
    if len(payload) != expected:
        raise SystemExit(f"{layout}: unexpected payload size {len(payload)} != {expected}")
    output.write_bytes(payload)
    print(f"VELA MAP: {layout} -> {len(payload)} bytes")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream-root", required=True, type=Path)
    args = parser.parse_args()
    root = args.upstream_root.resolve()

    south = build_vela_south()
    center = build_vela_center()
    grove = build_vela_grove()

    # Acceptance-path invariant: the Phase 3 encounter trigger must remain tall grass.
    if center[16][10] != TALL_GRASS:
        raise SystemExit("Vela Center controlled encounter tile moved or lost tall-grass semantics")
    if center[10][10] != CRYSTAL:
        raise SystemExit("Vela Center landmark tile moved")

    write_map(root, "LittlerootTown", south)
    write_map(root, "Route101", center)
    write_map(root, "OldaleTown", grove)
    print("PHASE4 VELA WORLD MAPS PASS: 3 connected 20x20 layouts use the owned Vela visual vocabulary")


if __name__ == "__main__":
    main()
